from __future__ import annotations

from typing import Protocol

from app.domain.media.models import MediaCandidate
from app.domain.planning.models import ShotPlan
from app.domain.projects.models import TimelineProject
from app.domain.rendering.models import RenderManifest, RenderResult, RenderSpec


class ProjectStoreError(Exception):
    def __init__(self, path: str, cause: Exception) -> None:
        self.path = path
        self.cause = cause
        super().__init__(f"ProjectStore error at {path}: {cause}")


class ProjectStore(Protocol):
    def project_dir(self, task_id: str, *, make: bool = False) -> str: ...
    def save_script(self, task_id: str, script: str) -> None: ...
    def load_script(self, task_id: str) -> str | None: ...
    def exists(self, task_id: str) -> bool: ...
    def save_shot_plan(self, task_id: str, plan: ShotPlan) -> None: ...
    def load_shot_plan(self, task_id: str) -> ShotPlan | None: ...
    def save_timeline(self, task_id: str, project: TimelineProject) -> None: ...
    def load_timeline(self, task_id: str) -> TimelineProject | None: ...
    def save_render_spec(self, task_id: str, spec: RenderSpec) -> None: ...
    def load_render_spec(self, task_id: str) -> RenderSpec | None: ...
    def save_render_manifest(self, task_id: str, manifest: RenderManifest) -> None: ...
    def load_render_manifest(self, task_id: str) -> RenderManifest | None: ...
    def save_render_result(self, task_id: str, result: RenderResult) -> None: ...
    def load_render_result(self, task_id: str) -> RenderResult | None: ...
    def save_media_candidates(
        self, task_id: str, candidates: list[MediaCandidate]
    ) -> None: ...
    def load_media_candidates(self, task_id: str) -> list[MediaCandidate]: ...
    def save_selected_media(self, task_id: str, selected: list[MediaCandidate]) -> None: ...
    def load_selected_media(self, task_id: str) -> list[MediaCandidate]: ...
